name: img_rtv
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  # - cudatoolkit=11.2
  - faiss-cpu
  - torchvision
  - pytorch-cuda
  - pytorch
  - pip:
    - opencv-python
    - scikit-image
    - streamlit
    - streamlit-cropper
